apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system-deploy
  namespace: solar-system
  labels:
    app: solar-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: nginx
        name: solar-system
